# Generated by Django 4.2.7 on 2023-12-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_balance',
            field=models.FloatField(default=1000000),
        ),
    ]
